#PlayerAbilityLib configuration file
#
#If alwaysLogTamperWarnings is set to false, external update messages will be logged only once per game session
#Tue Jun 30 20:08:39 UTC 2026
alwaysLogTamperWarnings=true
